name: Update server production
run-name: ${{ github.actor }} push in Main branch 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: sudo chmod +x ${{ github.workspace }}/.github/worflows/update.sh
      - run: sudo ${{ github.workspace }}/.github/workflows/update.sh
